# Font
font_family      AdwaitaMono Nerd Font
font_size 10.4

# Cursor
cursor #33ccff
cursor_blink_interval 0.5
cursor_trail 3

# Terminal bell
enable_audio_bell no
visual_bell_duration 0.0
window_alert_on_bell no

# Layout
window_margin_width 5
confirm_os_window_close 0

# Color
foreground #3ff8f5
#foreground #65c3b2
background #18192a
color0 #18192a

background_opacity 0.75
dynamic_background_opacity   yes

# shell
shell zsh

# Keys
kitty_mod alt

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

map kitty_mod+k       scroll_line_up
map kitty_mod+j       scroll_line_down


map kitty_mod+equal       change_font_size all +1.0
map kitty_mod+minus       change_font_size all -1.0


map kitty_mod+ctrl+equal set_background_opacity +0.05
map kitty_mod+ctrl+minus set_background_opacity -0.05
